### ISSUE TITLE
Cannot Log-In

### ISSUE THREAD

**Issue by skanda890** [tolgee/tolgee-cli#118]
When attempting to log in using a valid API key, the process encounters an issue that results in the error message "error: missing required argument 'API Key'." This error indicates that, despite providing what appears to be a correct and valid API key, the system is not recognizing it as such.

Tolgee version: 2.2.0

**Comment by stepan662** [comment]
Hey, could you specify how to reproduce the issue? Are you providing the api key through config or an CLI parameter?

**Comment by skanda890** [comment]
> Hey, could you specify how to reproduce the issue? Are you providing the api key through config or an CLI parameter?

I use the command "tolgee login <api-key>". I use the actual api key.

**Comment by stepan662** [comment]
And if you specify the api key as a parameter `--api-key` does it work then?

**Comment by stepan662** [comment]
So if I follow correctly you do:
```
tolgee login <api-key>
```

and then:

```
tolgee push
```

and it gives you "error: missing required argument 'API Key'."

This can happen when the api key is associated with different project than is specified in tolgeerc file, because then it's not used for push command. Could you check if the API key is associated with correct project. And also what error does it give you when you skip the login and provide the API key directly (`tolgee push --api-key=<...>`)?

**Comment by stepan662** [comment]
You can also use `--verbose` parameter, that should also print error stack.

**Comment by skanda890** [comment]
I don't use Tolgee CLI now.
