### ISSUE TITLE
--overwrite not working, missing argument 'path'

### ISSUE THREAD

**Issue by Arjan-Zuidema** [tolgee/tolgee-cli#53]
I get an error trying to pull strings using the cli:

```
> dotenv -c production tolgee pull --overwrite ./public/locales

error: missing required argument 'path'
```

I am using dotenv to load the `API_KEY`
Using version CLI version 1.2.0

Without the --overwrite everything works fine. But I want to automate this on CI so I cannot use the interactive mode.

**Comment by cyyynthia** [comment]
Hey there, sorry to hear you're having troubles!

This problem seems odd, as this command is e2e tested and the `--overwrite` argument should be working just fine. 

I recall using `dotenv -- (command...)` back when I was using dotenv, could you give this a try? The double dash should tell dotenv to consume the command "as is", as it might be currently consuming things it shouldn't (such as the `--override`) parameter leading to the problem you're encountering.

**Comment by Arjan-Zuidema** [comment]
Ah yes, that seems to do the trick. Thanks!

Also it would be nice to have the .env reading built-in 🙂
