### ISSUE TITLE
`tolgee sync` fails with warnings: `Dynamic default value`

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-cli#54]
The `tolgee sync` command fails with the following warning:

```
line 123: Dynamic default value
```

It corresponds to that translation code:

```ts
<T
  keyName="account.apiTokens.deleteConfirmationMessage"
  params={{
    strong: <strong>{apiTokens?.find(byId(deletingId))?.name}</strong>,
  }}
/>;
```

Is there anything I do wrong here?

**Comment by cyyynthia** [comment]
It seems you're not doing anything wrong here; the extractor parser is probably getting confused by this expression and fails to properly understand the expression.

You can silence this warning using the [`@tolgee-ignore`](https://tolgee.io/tolgee-cli/extraction/magic-comments#tolgee-ignore) magic comment if you wish, though it'll emit a warning again once the issue is fixed reminding you to remove it as it'll no longer be necessary.
